// Imports CJdropshipping products through the official API (no scraping: CJ's site is bot-protected).
//
//   npm run fetch-cj -- <slug-prefix>            verify: every listing, variant, stock and US shipping
//   npm run fetch-cj -- <slug-prefix> --apply    also save photos, costs, stock and storefront prices
//
// e.g. `npm run fetch-cj -- lamp-` for the lamp collections.
//
// For each CJDROPSHIPPING listing row in data/product-sourcing.tsv whose slug starts with the prefix:
//   - looks the listing up by the pid in its URL, checks CJ still has it on sale, and finds the
//     exact variant named in the row's `option` (the variant name exactly as CJ shows it, e.g.
//     "Monochrome Warm Light-Red Table Lamp-US")
//   - reads the variant's price, packed size and weight, its stock across CJ warehouses, and the
//     cheapest shipping option from CJ's China warehouse to the US
// With --apply:
//   - data/cj-variants.tsv gets the variant id, costs, stock and package (the seed turns these
//     into orderable supplier listings; fulfilment orders by variant id)
//   - frontend/services/lamp-offers.ts gets each product's retail price (the company floor:
//     2x item + shipping, ending .99), whether it can be bought, delivery estimate and package
//   - the product photo is saved as frontend/public/images/products/<slug>-<hash>.jpg: the pick
//     in data/cj-photos.tsv (a photo from the same CJ listing, optionally cropped to drop spec
//     text) or else the variant's own photo. The content hash in the name means a changed photo
//     gets a new URL, so browsers and the image cache never keep showing an older one.
// Then run `npm run db:seed` to load it.
//
// Needs CJ_API_KEY in backend/.env (CJ dashboard > Settings > API).

import "dotenv/config";
import { createHash } from "node:crypto";
import { existsSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import sharp from "sharp";
import { floorRetailCents } from "../src/modules/pricing/pricing.ts";
import { CJ_VARIANT_COLUMNS, DATA_DIR, parseCjVariants, type CjVariantRow } from "../src/modules/sourcing/sourcing-sheet.ts";
import { CjClient, cjPidFromUrl, usdToCents, type CjProduct } from "../src/modules/suppliers/cj.ts";

const IMAGES_DIR = fileURLToPath(new URL("../../frontend/public/images/products/", import.meta.url));
const OFFERS_FILE = fileURLToPath(new URL("../../frontend/services/lamp-offers.ts", import.meta.url));
const SOURCING = `${DATA_DIR}product-sourcing.tsv`;
const VARIANTS = `${DATA_DIR}cj-variants.tsv`;
const PHOTOS = `${DATA_DIR}cj-photos.tsv`;
const ON_SALE = "3";

const usd = (cents: number) => (cents / 100).toFixed(2);
const cm = (mm: number | undefined) => String(Math.round((mm ?? 0) / 10 * 10) / 10);

/** CJ's "4-7" shipping days, plus 2-5 business days for CJ to process and dispatch. */
export function deliveryEstimate(aging: string): string {
  const [lo, hi = lo] = (aging.match(/\d+/g) ?? []).map(Number);
  if (lo === undefined) return "Ships in 7-15 business days";
  return `Arrives in ${lo + 2}-${hi! + 5} business days`;
}

/** What the product page shows under Dimensions until we measure the product itself. */
export function packageLabel(r: Pick<CjVariantRow, "packageCm" | "weightKg">): string {
  if (!r.packageCm) return "To be confirmed";
  return `Ships boxed: ${r.packageCm.replaceAll(" x ", " × ")} cm${r.weightKg ? `, ${r.weightKg} kg` : ""}`;
}

export function offersSource(rows: CjVariantRow[]): string {
  const entries = [...rows]
    .sort((a, b) => a.productSlug.localeCompare(b.productSlug))
    .map((r) => {
      const priceCents = floorRetailCents({ unitCostCents: r.unitCostCents, shippingCostCents: r.shippingCostCents });
      const available = r.stock > 0 && r.unitCostCents > 0;
      return `  "${r.productSlug}": { priceCents: ${priceCents}, available: ${available}, shippingEstimate: "${deliveryEstimate(r.deliveryDays)}", dimensions: "${packageLabel(r)}", image: "${r.image}" },`;
    });
  return `// Generated by \`npm run fetch-cj -- lamp- --apply\` in backend/. Do not edit by hand:
// re-run the import to refresh prices, stock and delivery times from CJdropshipping.

export interface LampOffer {
  priceCents: number;
  available: boolean;
  shippingEstimate: string;
  dimensions: string;
  image: string;
}

export const lampOffers: Record<string, LampOffer> = {
${entries.join("\n")}
};
`;
}

/** data/cj-photos.tsv: product_slug, image_url, crop ("x0,y0,x1,y1" as fractions, or blank). */
function loadPhotoPicks(): Map<string, { url: string; crop: number[] | null }> {
  const picks = new Map<string, { url: string; crop: number[] | null }>();
  if (!existsSync(PHOTOS)) return picks;
  for (const line of readFileSync(PHOTOS, "utf8").replace(/\r/g, "").split("\n").slice(1)) {
    const [slug, url, crop] = line.split("\t");
    if (slug && url) picks.set(slug, { url, crop: crop ? crop.split(",").map(Number) : null });
  }
  return picks;
}

/**
 * Catalogue-ready JPEG: first frame only (some CJ photos are GIFs), optional crop to drop spec
 * text, a cropped photo padded to the 4:5 tile with its own background colour, max 1000px wide.
 */
export async function catalogueJpeg(input: Buffer, crop: number[] | null): Promise<Buffer> {
  let img = sharp(input, { pages: 1 }).rotate();
  if (crop) {
    const { width = 0, height = 0 } = await img.metadata();
    const [x0, y0, x1, y1] = crop as [number, number, number, number];
    const box = { left: Math.round(x0 * width), top: Math.round(y0 * height), width: Math.round((x1 - x0) * width), height: Math.round((y1 - y0) * height) };
    const cut = await img.extract(box).toBuffer();
    // Backdrop colour for the padding: the corner that agrees most with the other three, so a
    // label or shadow sitting in one corner doesn't tint the padding.
    const corners = await Promise.all(
      [
        [0, 0],
        [box.width - 1, 0],
        [0, box.height - 1],
        [box.width - 1, box.height - 1],
      ].map(async ([left, top]) => {
        const { data } = await sharp(cut).extract({ left: left!, top: top!, width: 1, height: 1 }).raw().toBuffer({ resolveWithObject: true });
        return [data[0]!, data[1]!, data[2]!];
      }),
    );
    const distance = (a: number[], b: number[]) => a.reduce((s, v, i) => s + Math.abs(v - b[i]!), 0);
    const [r, g, b] = corners.reduce((best, c) =>
      corners.reduce((s, o) => s + distance(c, o), 0) < corners.reduce((s, o) => s + distance(best, o), 0) ? c : best,
    );
    const background = { r: r!, g: g!, b: b! };
    const w = box.width;
    const h = box.height;
    const target = w / h > 0.8 ? { w, h: Math.round(w / 0.8) } : { w: Math.round(h * 0.8), h };
    img = sharp(cut).extend({
      top: Math.floor((target.h - h) / 2),
      bottom: Math.ceil((target.h - h) / 2),
      left: Math.floor((target.w - w) / 2),
      right: Math.ceil((target.w - w) / 2),
      background,
    });
  }
  return img.resize({ width: 1000, withoutEnlargement: true }).flatten({ background: "#ffffff" }).jpeg({ quality: 84, mozjpeg: true }).toBuffer();
}

/** Saves a product photo as <slug>-<hash>.jpg, removes the product's older photos, returns its URL. */
export function savePhoto(slug: string, jpeg: Buffer, dir = IMAGES_DIR): string {
  const name = `${slug}-${createHash("sha1").update(jpeg).digest("hex").slice(0, 8)}.jpg`;
  const older = new RegExp(`^${slug}-(cj|[0-9a-f]{8})\\.jpg$`);
  for (const file of readdirSync(dir)) if (file !== name && older.test(file)) rmSync(`${dir}${file}`);
  writeFileSync(`${dir}${name}`, jpeg);
  return `/images/products/${name}`;
}

async function main() {
  const [prefix, ...flags] = process.argv.slice(2);
  if (!prefix) throw new Error("usage: npm run fetch-cj -- <slug-prefix> [--apply]");
  const apply = flags.includes("--apply");
  if (!process.env.CJ_API_KEY) throw new Error("Set CJ_API_KEY in backend/.env");
  const cj = new CjClient(process.env.CJ_API_KEY);

  const lines = readFileSync(SOURCING, "utf-8").replace(/\r/g, "").split("\n");
  const header = lines[0]!.split("\t");
  const col = (name: string) => header.indexOf(name);
  let variants = new Map<string, CjVariantRow>();
  try {
    if (existsSync(VARIANTS)) variants = parseCjVariants(readFileSync(VARIANTS, "utf8"));
  } catch (err) {
    console.log(`starting data/cj-variants.tsv over: ${err instanceof Error ? err.message : err}`);
  }
  const picks = loadPhotoPicks();
  const products = new Map<string, CjProduct | Error>();
  const problems: string[] = [];
  const checkedAt = new Date().toISOString().slice(0, 10);
  const seen = new Set<string>();
  let checked = 0;

  for (const line of lines.slice(1)) {
    const cells = line.split("\t");
    const [slug, platform, url, option] = [cells[col("product_slug")]!, cells[col("platform")], cells[col("url")] ?? "", cells[col("option")] ?? ""];
    if (!slug?.startsWith(prefix) || platform !== "CJDROPSHIPPING") continue;
    checked++;
    const fail = (why: string) => {
      problems.push(`${slug}: ${why}`);
      variants.delete(slug);
      console.log(`FAIL    ${slug}: ${why}`);
    };

    const pid = cjPidFromUrl(url);
    if (!pid) {
      fail(`no pid in ${url}`);
      continue;
    }
    if (!products.has(pid)) products.set(pid, await cj.product(pid).catch((err: Error) => err));
    const product = products.get(pid)!;
    if (product instanceof Error) {
      fail(`CJ has no product ${pid}: ${product.message}`);
      continue;
    }
    if (String(product.status) !== ON_SALE) {
      fail(`CJ lists "${product.productNameEn.slice(0, 50)}" as not on sale (status ${product.status})`);
      continue;
    }
    const variant = (product.variants ?? []).find((v) => v.variantKey === option);
    if (!variant) {
      fail(`no variant named "${option}" on "${product.productNameEn.slice(0, 50)}"`);
      continue;
    }

    // One supplier variant can back only one catalogue product (one listing per CJ variant).
    const twin = [...variants.values()].find(
      (v) => v.vid === variant.vid && v.productSlug !== slug && (seen.has(v.productSlug) || !v.productSlug.startsWith(prefix)),
    );
    if (twin) {
      fail(`same CJ variant as ${twin.productSlug}; pick another variant or drop one of them`);
      continue;
    }
    seen.add(slug);

    const stock = await cj
      .get<{ totalInventoryNum?: number }[]>(`/product/stock/queryByVid?vid=${encodeURIComponent(variant.vid)}`)
      .then((rows) => (rows ?? []).reduce((n, r) => n + (r.totalInventoryNum ?? 0), 0))
      .catch((err: Error) => {
        problems.push(`${slug}: stock check failed (${err.message}); listed as out of stock`);
        return 0;
      });
    const [ship] = await cj.freight(variant.vid).catch(() => []);
    if (!ship) {
      fail(`CJ has no shipping option to the US for "${option}"`);
      continue;
    }

    const row: CjVariantRow = {
      productSlug: slug,
      pid,
      vid: variant.vid,
      variantKey: option,
      unitCostCents: usdToCents(variant.variantSellPrice),
      shippingCostCents: usdToCents(ship.logisticPrice),
      logistic: ship.logisticName,
      deliveryDays: ship.logisticAging ?? "",
      stock,
      packageCm: variant.variantLength ? [variant.variantLength, variant.variantWidth, variant.variantHeight].map(cm).join(" x ") : "",
      weightKg: Math.round((variant.variantWeight ?? 0) / 10) / 100,
      image: variants.get(slug)?.image ?? "",
      checkedAt,
    };
    variants.set(slug, row);
    console.log(
      `ok      ${slug}: $${usd(row.unitCostCents)} + $${usd(row.shippingCostCents)} ${row.logistic} -> $${usd(floorRetailCents(row))}, stock ${stock}`,
    );

    if (!apply) continue;
    const pick = picks.get(slug);
    const photo = pick?.url || variant.variantImage || product.bigImage;
    const image = photo ? await fetch(photo).catch(() => null) : null;
    if (!image?.ok) {
      problems.push(`${slug}: photo download failed`);
      continue;
    }
    row.image = savePhoto(slug, await catalogueJpeg(Buffer.from(await image.arrayBuffer()), pick?.crop ?? null));
  }

  const verified = [...variants.keys()].filter((s) => s.startsWith(prefix) && seen.has(s)).length;
  console.log(`\n${verified}/${checked} verified on CJ: on sale, exact variant found, ships to the US`);
  if (apply) {
    const rows = [...variants.values()].sort((a, b) => a.productSlug.localeCompare(b.productSlug));
    const tsv = rows.map((r) =>
      [r.productSlug, r.pid, r.vid, r.variantKey, usd(r.unitCostCents), usd(r.shippingCostCents), r.logistic, r.deliveryDays, r.stock, r.packageCm, r.weightKg, r.image, r.checkedAt].join("\t"),
    );
    writeFileSync(VARIANTS, [CJ_VARIANT_COLUMNS.join("\t"), ...tsv].join("\n") + "\n");
    writeFileSync(OFFERS_FILE, offersSource(rows));
    console.log(`wrote ${rows.length} variants to data/cj-variants.tsv and storefront prices to frontend/services/lamp-offers.ts`);
  }
  if (problems.length) console.log(`\n${problems.length} need attention:\n  ${problems.join("\n  ")}`);
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  main().catch((err) => {
    console.error(err instanceof Error ? err.message : err);
    process.exit(1);
  });
}
