// Mock dataset standing in for the backend API until it exists.
// Only the services/ layer imports this file. Swap each service function to a
// real fetch() when the backend endpoints land; nothing else needs to change.
//

import type { Product, RoomStyle } from "@shared/types";

export const styles: RoomStyle[] = [
  {
    slug: "sleek-masculine",
    name: "Sleek Masculine",
    tagline: "Dark linens, matte black, low warm light.",
    coverImage: "/images/rooms/hero.jpg",
  },
  {
    slug: "warm-minimal",
    name: "Warm Minimal",
    tagline: "Raw oak, soft whites and very little else.",
    coverImage: "/images/rooms/oak-and-linen.jpg",
  },
  {
    slug: "dark-academia",
    name: "Dark Academia",
    tagline: "Old books, brass lamps, deep wood.",
    coverImage: "/images/rooms/dark-academia-cover.jpg",
  },
  {
    slug: "gaming-minimal",
    name: "Gaming Minimal",
    tagline: "A clean desk that still means business.",
    coverImage: "/images/rooms/gaming-cover.jpg",
  },
  {
    slug: "modern-luxury",
    name: "Modern Luxury",
    tagline: "Hotel-suite calm with a few loud pieces.",
    coverImage: "/images/rooms/gallery-suite.jpg",
  },
];

const p = (
  id: string,
  name: string,
  priceCents: number,
  category: Product["category"],
  styles: string[],
  color: string,
  description: string,
  dimensions: string,
  available = true,
): Product => ({
  id,
  slug: id,
  name,
  priceCents,
  image: `/images/products/${id}.jpg`,
  category,
  styles,
  color,
  description,
  dimensions,
  shippingEstimate: "Ships in 3-5 business days",
  available,
});

export const products: Product[] = [
  p("mushroom-lamp", "Mushroom Table Lamp", 2499, "lighting", ["warm-minimal", "gaming-minimal"], "Mustard",
    "A soft dome of light for a nightstand or desk corner. Dimmable LED, USB-C powered.", "32 x 24 cm"),
  p("arc-floor-lamp", "Arc Floor Lamp", 8900, "lighting", ["sleek-masculine", "warm-minimal", "modern-luxury"], "Graphite",
    "Steel stem, tilting shade. Throws light over a chair or bed without taking floor space.", "165 x 30 cm"),
  p("dome-pendant", "Dome Pendant Light", 4250, "lighting", ["warm-minimal"], "Matte white",
    "A simple spun-metal pendant that works over a bed, desk or reading chair.", "28 x 22 cm, 1.5 m cord"),
  p("tripod-table-lamp", "Tripod Linen Lamp", 5400, "lighting", ["warm-minimal", "sleek-masculine", "modern-luxury"], "Oak and linen",
    "Solid oak legs and a linen drum shade. Warm, even light for a bedside.", "48 x 30 cm"),
  p("typography-print", "Be Fearless Print", 1899, "wall-art", ["sleek-masculine", "gaming-minimal", "warm-minimal"], "Black",
    "Matte giclee print in a slim black frame. Lean it or hang it.", "50 x 70 cm"),
  p("oak-gallery-frame", "Oak Gallery Frame", 3200, "wall-art", ["warm-minimal", "dark-academia", "sleek-masculine", "modern-luxury"], "Natural oak",
    "Deep-profile oak frame with a white mount. Fits standard A2 prints.", "50 x 70 cm"),
  p("woven-wool-rug", "Woven Wool Rug", 12900, "rugs", ["warm-minimal", "modern-luxury", "sleek-masculine", "dark-academia"], "Ivory",
    "Hand-loomed wool with a low pile. Soft underfoot, easy to vacuum.", "160 x 230 cm"),
  p("linen-throw-pillow", "Linen Throw Pillow", 2200, "decor", ["sleek-masculine", "warm-minimal", "modern-luxury"], "White",
    "Stonewashed linen cover with a feather insert. Removable, machine washable.", "50 x 50 cm"),
  p("pampas-bundle", "Dried Pampas Bundle", 1650, "decor", ["warm-minimal", "modern-luxury", "sleek-masculine"], "Natural",
    "A full bundle of dried pampas stems. Vase not included.", "Stems approx. 80 cm"),
  p("shell-chair", "Molded Shell Chair", 7400, "seating", ["warm-minimal", "gaming-minimal"], "White",
    "Molded shell seat on beech dowel legs. Light enough to move around.", "81 x 62 x 59 cm"),
  p("cloud-lounge-chair", "Cloud Lounge Chair", 24900, "seating", ["modern-luxury", "warm-minimal"], "Powder blue",
    "Deep, upholstered lounge chair with oak legs. The reading seat you will actually use.", "84 x 76 x 80 cm"),
  p("swing-arm-desk-lamp", "Swing-Arm Desk Lamp", 4600, "lighting", ["sleek-masculine", "gaming-minimal"], "Black",
    "Counterweighted arm that holds any angle. Clamps to a desk or wall-mounts by the bed.", "Reach 70 cm"),
  p("banker-lamp", "Brass Banker Lamp", 6400, "lighting", ["dark-academia", "modern-luxury"], "Brass",
    "Brushed brass base and a warm fabric shade. Pull-chain switch.", "52 x 28 cm"),
  p("walnut-keyboard", "Mechanical Keyboard", 11900, "desk", ["gaming-minimal"], "Smoke",
    "Hot-swappable 75% board with a walnut wrist rest. Quiet linear switches.", "33 x 14 cm"),
  p("walnut-monitor-riser", "Walnut Monitor Riser", 6900, "desk", ["gaming-minimal", "dark-academia"], "Walnut",
    "Lifts your screen to eye level and hides the clutter underneath.", "90 x 24 x 10 cm"),
  p("edison-globe-lamp", "Edison Globe Lamp", 3800, "lighting", ["dark-academia"], "Amber glass",
    "Oversized filament bulb on a brass socket. Dim it all the way down for evenings.", "30 x 18 cm"),
  p("leather-atlas", "Leather-Bound Atlas", 2900, "decor", ["dark-academia"], "Oxblood",
    "A reproduction antique atlas with a worn leather spine. Shelf decor that is also readable.", "32 x 24 x 6 cm"),
  p("pillar-candle", "Flicker LED Pillar Candle", 1400, "decor", ["dark-academia"], "Ivory",
    "Real-wax LED candle with a moving flame. Timer switch, no open fire.", "20 x 7.5 cm", false),
  p("felt-desk-mat", "Wool Felt Desk Mat", 3400, "desk", ["gaming-minimal"], "Charcoal",
    "Thick merino felt with a non-slip base. Covers keyboard and mouse.", "90 x 40 cm"),
  p("studio-monitor-speakers", "Compact Studio Speakers", 15900, "desk", ["gaming-minimal"], "White",
    "Powered bookshelf speakers with Bluetooth and a headphone out.", "15 x 10 x 13 cm (each)"),
  p("living-sofa", "Tufted Leather Chesterfield Sofa", 189900, "seating", ["sleek-masculine"], "Black leather",
    "Deep-buttoned leather sofa on turned wooden feet. Placeholder listing.", "220 x 95 x 75 cm", false),
  p("living-armchair", "Leather Lounge Armchair", 59900, "seating", ["sleek-masculine", "warm-minimal"], "Black leather and oak",
    "Padded leather seat on a solid oak frame. Placeholder listing.", "80 x 80 x 85 cm", false),
  p("living-coffee-table", "Oak Coffee Table", 34900, "furniture", ["sleek-masculine", "warm-minimal"], "Oak and stone",
    "Low table with a stone top and oak legs. Placeholder listing.", "120 x 60 x 42 cm", false),
  p("living-rug", "Plaid Wool Area Rug", 42900, "rugs", ["sleek-masculine", "warm-minimal"], "Taupe and blush",
    "Hand-finished plaid wool rug with a low pile. Placeholder listing.", "240 x 170 cm", false),
  p("living-side-table", "Oak Side Table", 18900, "furniture", ["sleek-masculine", "warm-minimal"], "Oak",
    "Small two-tier side table in solid oak. Placeholder listing.", "45 x 45 x 55 cm", false),
  p("living-vase", "Ceramic Bud Vase", 4200, "decor", ["sleek-masculine", "warm-minimal"], "Ivory",
    "Tall ceramic vase with a matte glaze. Placeholder listing.", "10 x 10 x 40 cm", false),
  p("living-tv-stand", "Walnut Media Console", 74900, "furniture", ["sleek-masculine", "gaming-minimal"], "Walnut",
    "Low media console with a long walnut top and soft-close drawers. Placeholder listing.", "160 x 45 x 50 cm", false),
  p("living-art", "Checkerboard Framed Print", 8900, "wall-art", ["sleek-masculine", "warm-minimal"], "Oak frame",
    "Giclee print in a solid oak frame. Placeholder listing.", "70 x 90 cm", false),
  p("living-pendant", "Globe Pendant Light", 12900, "lighting", ["sleek-masculine", "warm-minimal"], "Matte white",
    "Frosted globe pendant on a fine cord. Placeholder listing.", "35 cm diameter, 1.2 m drop", false),
  p("living-bookshelf", "Worn Oak Bookshelf", 49900, "furniture", ["sleek-masculine", "warm-minimal"], "Worn oak",
    "Five-shelf open bookcase in reclaimed-style oak. Placeholder listing.", "90 x 35 x 180 cm", false),
  p("living-plant-a", "Potted Fern Plant", 3900, "decor", ["warm-minimal", "sleek-masculine"], "Green",
    "Leafy potted plant in a terracotta pot. Placeholder listing.", "45 cm tall", false),
  p("living-plant-b", "Potted Monstera Plant", 5900, "decor", ["warm-minimal", "sleek-masculine"], "Green",
    "Large-leaf potted plant in a terracotta pot. Placeholder listing.", "70 cm tall", false),
];
