// Mock dataset standing in for the backend API until it exists.
// Only the services/ layer imports this file. Swap each service function to a
// real fetch() when the backend endpoints land; nothing else needs to change.
//

import type { Product, RoomStyle } from "@shared/types";
import { catalogProducts } from "./catalog";
import { lampOffers } from "./lamp-offers";

export const styles: RoomStyle[] = [
  {
    slug: "sleek-masculine",
    name: "Sleek Masculine",
    tagline: "Dark linens, matte black, low warm light.",
    coverImage: "/images/rooms/hero.jpg",
  },
  {
    slug: "warm-minimal",
    name: "Warm Minimal",
    tagline: "Raw oak, soft whites and very little else.",
    coverImage: "/images/rooms/oak-and-linen.jpg",
  },
  {
    slug: "dark-academia",
    name: "Dark Academia",
    tagline: "Old books, brass lamps, deep wood.",
    coverImage: "/images/rooms/dark-academia-cover.jpg",
  },
  {
    slug: "gaming-minimal",
    name: "Gaming Minimal",
    tagline: "A clean desk that still means business.",
    coverImage: "/images/rooms/gaming-cover.jpg",
  },
  {
    slug: "modern-luxury",
    name: "Modern Luxury",
    tagline: "Hotel-suite calm with a few loud pieces.",
    coverImage: "/images/rooms/gallery-suite.jpg",
  },
  {
    slug: "neocolonial",
    name: "Neocolonial",
    tagline: "Leather, mahogany and firelight, done with restraint.",
    coverImage: "/images/rooms/neocolonial-parlour.jpg",
  },
];

// Lamps: 100 CJdropshipping products (backend/data/product-sourcing.tsv). Price, stock and
// delivery time come from lamp-offers.ts, written by `npm run fetch-cj` in backend/: retail is
// the company floor (2x CJ item + US shipping). The price below is only the fallback before the
// first import, and a lamp is unbuyable until imported in stock.
const p = (id: string, name: string, fallbackCents: number, color: string, description: string): Product => ({
  id,
  slug: id,
  name,
  priceCents: lampOffers[id]?.priceCents ?? fallbackCents,
  image: lampOffers[id]?.image ?? `/images/products/${id}.jpg`,
  category: "lighting",
  styles: [],
  color,
  description,
  dimensions: lampOffers[id]?.dimensions ?? "To be confirmed",
  shippingEstimate: lampOffers[id]?.shippingEstimate ?? "Ships in 7-15 business days",
  available: lampOffers[id]?.available ?? false,
});

const lampProducts: Product[] = [
  p("lamp-rechargeable-metal-accent-lamp", "Rechargeable Metal Accent Lamp", 1299, "",
    "Clean lines, matte finishes, understated design. From our Modern Essentials collection."),
  p("lamp-black-rechargeable-breathing-lamp", "Black Rechargeable Breathing Lamp", 1399, "Black",
    "Clean lines, matte finishes, understated design. From our Modern Essentials collection."),
  p("lamp-silver-rechargeable-breathing-lamp", "Silver Rechargeable Breathing Lamp", 1399, "Silver",
    "Clean lines, matte finishes, understated design. From our Modern Essentials collection."),
  p("lamp-black-and-copper-led-table-lamp", "Black-and-Copper LED Table Lamp", 2499, "",
    "Clean lines, matte finishes, understated design. From our Modern Essentials collection."),
  p("lamp-double-sided-led-touch-lamp", "Double-Sided LED Touch Lamp", 1599, "",
    "Clean lines, matte finishes, understated design. From our Modern Essentials collection."),
  p("lamp-white-magnetic-mini-lamp", "White Magnetic Mini Lamp", 499, "White",
    "Clean lines, matte finishes, understated design. From our Modern Essentials collection."),
  p("lamp-black-magnetic-mini-lamp", "Black Magnetic Mini Lamp", 499, "Black",
    "Clean lines, matte finishes, understated design. From our Modern Essentials collection."),
  p("lamp-matte-black-minimalist-wall-light", "Matte Black Minimalist Wall Light", 1699, "Black",
    "Clean lines, matte finishes, understated design. From our Modern Essentials collection."),
  p("lamp-modern-white-circular-wall-light", "Modern White Circular Wall Light", 1299, "White",
    "Clean lines, matte finishes, understated design. From our Modern Essentials collection."),
  p("lamp-rotating-bedside-led-lamp", "Rotating Bedside LED Lamp", 699, "",
    "Clean lines, matte finishes, understated design. From our Modern Essentials collection."),
  p("lamp-walnut-mushroom-bedside-lamp", "Walnut Mushroom Bedside Lamp", 2299, "Walnut",
    "Soft lighting, inviting bedrooms, warm colors. From our Warm & Cozy collection."),
  p("lamp-beech-mushroom-bedside-lamp", "Beech Mushroom Bedside Lamp", 2299, "Beech",
    "Soft lighting, inviting bedrooms, warm colors. From our Warm & Cozy collection."),
  p("lamp-gold-antique-cordless-lamp", "Gold Antique Cordless Lamp", 1099, "Gold",
    "Soft lighting, inviting bedrooms, warm colors. From our Warm & Cozy collection."),
  p("lamp-pleated-walnut-floor-lamp", "Pleated Walnut Floor Lamp", 4899, "Walnut",
    "Soft lighting, inviting bedrooms, warm colors. From our Warm & Cozy collection."),
  p("lamp-wood-grain-pleated-lamp-warm-light", "Wood Grain Pleated Lamp, Warm Light", 4899, "",
    "Soft lighting, inviting bedrooms, warm colors. From our Warm & Cozy collection."),
  p("lamp-fabric-shade-bedside-lamp", "Fabric Shade Bedside Lamp", 799, "",
    "Soft lighting, inviting bedrooms, warm colors. From our Warm & Cozy collection."),
  p("lamp-dual-usb-fabric-bedside-lamp", "Dual-USB Fabric Bedside Lamp", 799, "",
    "Soft lighting, inviting bedrooms, warm colors. From our Warm & Cozy collection."),
  p("lamp-warm-dimmable-spiral-lamp", "Warm Dimmable Spiral Lamp", 2699, "",
    "Soft lighting, inviting bedrooms, warm colors. From our Warm & Cozy collection."),
  p("lamp-soft-white-glass-globe-wall-light", "Soft White Glass Globe Wall Light", 2999, "",
    "Soft lighting, inviting bedrooms, warm colors. From our Warm & Cozy collection."),
  p("lamp-red-retro-metal-table-lamp", "Red Retro Metal Table Lamp", 2899, "Red",
    "Nostalgic shapes, playful colors, vintage influences. From our Retro Revival collection."),
  p("lamp-milk-green-retro-table-lamp", "Milk Green Retro Table Lamp", 2899, "Milk green",
    "Nostalgic shapes, playful colors, vintage influences. From our Retro Revival collection."),
  p("lamp-chrome-retro-table-lamp", "Chrome Retro Table Lamp", 2899, "Chrome",
    "Nostalgic shapes, playful colors, vintage influences. From our Retro Revival collection."),
  p("lamp-beige-retro-table-lamp", "Beige Retro Table Lamp", 2899, "Beige",
    "Nostalgic shapes, playful colors, vintage influences. From our Retro Revival collection."),
  p("lamp-red-retro-floor-lamp", "Red Retro Floor Lamp", 6399, "Red",
    "Nostalgic shapes, playful colors, vintage influences. From our Retro Revival collection."),
  p("lamp-green-retro-floor-lamp", "Green Retro Floor Lamp", 6399, "Green",
    "Nostalgic shapes, playful colors, vintage influences. From our Retro Revival collection."),
  p("lamp-retro-glass-shell-wall-lamp-green", "Retro Glass Shell Wall Lamp, Green", 3999, "Green",
    "Nostalgic shapes, playful colors, vintage influences. From our Retro Revival collection."),
  p("lamp-vintage-wrought-iron-wall-light-black", "Vintage Wrought Iron Wall Light, Black", 2599, "Black",
    "Nostalgic shapes, playful colors, vintage influences. From our Retro Revival collection."),
  p("lamp-vintage-wrought-iron-wall-light-gold", "Vintage Wrought Iron Wall Light, Gold", 2599, "Gold",
    "Nostalgic shapes, playful colors, vintage influences. From our Retro Revival collection."),
  p("lamp-vintage-country-iron-table-lamp", "Vintage Country Iron Table Lamp", 1399, "",
    "Nostalgic shapes, playful colors, vintage influences. From our Retro Revival collection."),
  p("lamp-gold-crystal-wall-sconce", "Gold Crystal Wall Sconce", 1699, "Gold",
    "Glass, gold accents, polished sophistication. From our Quiet Luxury collection."),
  p("lamp-black-crystal-wall-sconce", "Black Crystal Wall Sconce", 1699, "Black",
    "Glass, gold accents, polished sophistication. From our Quiet Luxury collection."),
  p("lamp-gold-modern-wall-light-small", "Gold Modern Wall Light, Small", 1699, "Gold",
    "Glass, gold accents, polished sophistication. From our Quiet Luxury collection."),
  p("lamp-gold-modern-wall-light-large", "Gold Modern Wall Light, Large", 1699, "Gold",
    "Glass, gold accents, polished sophistication. From our Quiet Luxury collection."),
  p("lamp-brushed-gold-circular-sconce", "Brushed Gold Circular Sconce", 1299, "Brushed gold",
    "Glass, gold accents, polished sophistication. From our Quiet Luxury collection."),
  p("lamp-coffee-gold-circular-sconce", "Coffee Gold Circular Sconce", 1299, "Coffee gold",
    "Glass, gold accents, polished sophistication. From our Quiet Luxury collection."),
  p("lamp-gold-rechargeable-ambient-lamp", "Gold Rechargeable Ambient Lamp", 1399, "Gold",
    "Glass, gold accents, polished sophistication. From our Quiet Luxury collection."),
  p("lamp-frosted-glass-globe-wall-lamp-18cm", "Frosted Glass Globe Wall Lamp, 18cm", 2999, "",
    "Glass, gold accents, polished sophistication. From our Quiet Luxury collection."),
  p("lamp-rechargeable-gold-bistro-table-lamp", "Rechargeable Gold Bistro Table Lamp", 0, "Gold",
    "Glass, gold accents, polished sophistication. From our Quiet Luxury collection."),
  p("lamp-solid-wood-nordic-table-lamp", "Solid Wood Nordic Table Lamp", 8299, "",
    "Wood, rattan, earthy finishes. From our Nature Inspired collection."),
  p("lamp-solid-wood-warm-light-lamp-3w", "Solid Wood Warm Light Lamp, 3W", 8299, "",
    "Wood, rattan, earthy finishes. From our Nature Inspired collection."),
  p("lamp-solid-wood-warm-light-lamp-5w", "Solid Wood Warm Light Lamp, 5W", 8299, "",
    "Wood, rattan, earthy finishes. From our Nature Inspired collection."),
  p("lamp-walnut-finish-wooden-accent-lamp", "Walnut Finish Wooden Accent Lamp", 5299, "Walnut",
    "Wood, rattan, earthy finishes. From our Nature Inspired collection."),
  p("lamp-black-wooden-accent-lamp", "Black Wooden Accent Lamp", 5299, "Black",
    "Wood, rattan, earthy finishes. From our Nature Inspired collection."),
  p("lamp-natural-rattan-ball-pendant", "Natural Rattan Ball Pendant", 3399, "Natural",
    "Wood, rattan, earthy finishes. From our Nature Inspired collection."),
  p("lamp-light-coffee-rattan-pendant", "Light Coffee Rattan Pendant", 3399, "Light coffee",
    "Wood, rattan, earthy finishes. From our Nature Inspired collection."),
  p("lamp-orange-toned-rattan-pendant", "Orange-Toned Rattan Pendant", 3399, "Orange",
    "Wood, rattan, earthy finishes. From our Nature Inspired collection."),
  p("lamp-bamboo-woven-chandelier", "Bamboo Woven Chandelier", 0, "",
    "Wood, rattan, earthy finishes. From our Nature Inspired collection."),
  p("lamp-handwoven-bamboo-dining-pendant", "Handwoven Bamboo Dining Pendant", 3899, "",
    "Wood, rattan, earthy finishes. From our Nature Inspired collection."),
  p("lamp-magnetic-floating-bulb-lamp-square-base", "Magnetic Floating Bulb Lamp, Square Base", 6499, "",
    "Bold forms, unusual silhouettes, eye-catching lighting. From our Statement Pieces collection."),
  p("lamp-magnetic-floating-bulb-lamp-round-base", "Magnetic Floating Bulb Lamp, Round Base", 6499, "",
    "Bold forms, unusual silhouettes, eye-catching lighting. From our Statement Pieces collection."),
  p("lamp-floating-moon-lamp-brown-base", "Floating Moon Lamp, Brown Base", 12199, "",
    "Bold forms, unusual silhouettes, eye-catching lighting. From our Statement Pieces collection."),
  p("lamp-rotating-moon-lamp-gray", "Rotating Moon Lamp, Gray", 2599, "Gray",
    "Bold forms, unusual silhouettes, eye-catching lighting. From our Statement Pieces collection."),
  p("lamp-rotating-moon-lamp-white", "Rotating Moon Lamp, White", 2599, "White",
    "Bold forms, unusual silhouettes, eye-catching lighting. From our Statement Pieces collection."),
  p("lamp-hot-air-balloon-table-lamp-red", "Hot Air Balloon Table Lamp, Red", 1299, "Red",
    "Bold forms, unusual silhouettes, eye-catching lighting. From our Statement Pieces collection."),
  p("lamp-hot-air-balloon-table-lamp-blue", "Hot Air Balloon Table Lamp, Blue", 1299, "Blue",
    "Bold forms, unusual silhouettes, eye-catching lighting. From our Statement Pieces collection."),
  p("lamp-geometric-resin-wall-lamp-green", "Geometric Resin Wall Lamp, Green", 1499, "Green",
    "Bold forms, unusual silhouettes, eye-catching lighting. From our Statement Pieces collection."),
  p("lamp-geometric-resin-wall-lamp-orange", "Geometric Resin Wall Lamp, Orange", 1499, "Orange",
    "Bold forms, unusual silhouettes, eye-catching lighting. From our Statement Pieces collection."),
  p("lamp-rechargeable-eye-care-desk-lamp-1800mah", "Rechargeable Eye-Care Desk Lamp, 1800mAh", 899, "",
    "Task lighting and practical modern desk lamps. From our Work & Focus collection."),
  p("lamp-rechargeable-eye-care-desk-lamp-2500mah", "Rechargeable Eye-Care Desk Lamp, 2500mAh", 899, "",
    "Task lighting and practical modern desk lamps. From our Work & Focus collection."),
  p("lamp-plug-in-reading-desk-lamp", "Plug-in Reading Desk Lamp", 899, "",
    "Task lighting and practical modern desk lamps. From our Work & Focus collection."),
  p("lamp-touch-sensor-reading-lamp-black", "Touch Sensor Reading Lamp, Black", 1299, "Black",
    "Task lighting and practical modern desk lamps. From our Work & Focus collection."),
  p("lamp-touch-sensor-reading-lamp-white", "Touch Sensor Reading Lamp, White", 1299, "White",
    "Task lighting and practical modern desk lamps. From our Work & Focus collection."),
  p("lamp-smart-desk-lamp-with-wireless-charger-black", "Smart Desk Lamp with Wireless Charger, Black", 1499, "Black",
    "Task lighting and practical modern desk lamps. From our Work & Focus collection."),
  p("lamp-smart-desk-lamp-with-wireless-charger-white", "Smart Desk Lamp with Wireless Charger, White", 1499, "White",
    "Task lighting and practical modern desk lamps. From our Work & Focus collection."),
  p("lamp-led-clock-desk-lamp-with-pen-holder-2000mah", "LED Clock Desk Lamp with Pen Holder, 2000mAh", 999, "",
    "Task lighting and practical modern desk lamps. From our Work & Focus collection."),
  p("lamp-led-clock-desk-lamp-with-pen-holder-3200mah", "LED Clock Desk Lamp with Pen Holder, 3200mAh", 999, "",
    "Task lighting and practical modern desk lamps. From our Work & Focus collection."),
  p("lamp-portable-rechargeable-lamp-with-flashlight", "Portable Rechargeable Lamp with Flashlight", 1299, "",
    "Task lighting and practical modern desk lamps. From our Work & Focus collection."),
  p("lamp-northern-lights-color-changing-lamp", "Northern Lights Color-Changing Lamp", 1199, "",
    "Color-changing and atmospheric lighting. From our Mood Makers collection."),
  p("lamp-northern-lights-cherry-blossom-lamp", "Northern Lights Cherry Blossom Lamp", 1199, "",
    "Color-changing and atmospheric lighting. From our Mood Makers collection."),
  p("lamp-aurora-borealis-galaxy-projector", "Aurora Borealis Galaxy Projector", 3699, "",
    "Color-changing and atmospheric lighting. From our Mood Makers collection."),
  p("lamp-16-color-crystal-water-ripple-lamp", "16-Color Crystal Water Ripple Lamp", 1099, "",
    "Color-changing and atmospheric lighting. From our Mood Makers collection."),
  p("lamp-rechargeable-water-ripple-lamp", "Crown Water Ripple Lamp", 499, "",
    "Color-changing and atmospheric lighting. From our Mood Makers collection."),
  p("lamp-tricolor-water-ripple-lamp", "Tricolor Water Ripple Lamp", 299, "",
    "Color-changing and atmospheric lighting. From our Mood Makers collection."),
  p("lamp-rgb-double-sided-ambient-lamp", "RGB Double-Sided Ambient Lamp", 1599, "",
    "Color-changing and atmospheric lighting. From our Mood Makers collection."),
  p("lamp-cloud-silicone-touch-lamp", "Cloud Silicone Touch Lamp", 999, "",
    "Color-changing and atmospheric lighting. From our Mood Makers collection."),
  p("lamp-black-rgb-corner-floor-lamp", "Black RGB Corner Floor Lamp", 9499, "Black",
    "Color-changing and atmospheric lighting. From our Mood Makers collection."),
  p("lamp-concrete-industrial-pendant-small", "Concrete Industrial Pendant, Small", 2999, "",
    "Architectural, industrial, and dark-accent lighting. From our Urban Edge collection."),
  p("lamp-concrete-industrial-pendant-large", "Concrete Industrial Pendant, Large", 2999, "",
    "Architectural, industrial, and dark-accent lighting. From our Urban Edge collection."),
  p("lamp-black-nordic-wall-light-single-head", "Black Nordic Wall Light, Single Head", 1099, "",
    "Architectural, industrial, and dark-accent lighting. From our Urban Edge collection."),
  p("lamp-black-architectural-wall-light-large", "Black Architectural Wall Light, Large", 1699, "Black",
    "Architectural, industrial, and dark-accent lighting. From our Urban Edge collection."),
  p("lamp-gray-architectural-wall-light-small", "Gray Architectural Wall Light, Small", 1699, "Gray",
    "Architectural, industrial, and dark-accent lighting. From our Urban Edge collection."),
  p("lamp-minimalist-aluminum-up-and-down-wall-lamp", "Minimalist Aluminum Up-and-Down Wall Lamp", 2699, "",
    "Architectural, industrial, and dark-accent lighting. From our Urban Edge collection."),
  p("lamp-brushed-black-circular-wall-sconce", "Brushed Black Circular Wall Sconce", 1299, "Brushed black",
    "Architectural, industrial, and dark-accent lighting. From our Urban Edge collection."),
  p("lamp-black-modern-pendant-small", "Black Modern Pendant, Small", 2899, "Black",
    "Architectural, industrial, and dark-accent lighting. From our Urban Edge collection."),
  p("lamp-black-modern-pendant-large", "Black Modern Pendant, Large", 2899, "Black",
    "Architectural, industrial, and dark-accent lighting. From our Urban Edge collection."),
  p("lamp-black-arc-floor-lamp", "Black Arc Floor Lamp", 4599, "Black",
    "Floor lamps and larger decorative pieces. From our Living Room Favorites collection."),
  p("lamp-adjustable-led-reading-floor-lamp", "Adjustable LED Reading Floor Lamp", 2799, "",
    "Floor lamps and larger decorative pieces. From our Living Room Favorites collection."),
  p("lamp-walnut-pleated-floor-lamp-remote-dimming", "Walnut Pleated Floor Lamp, Remote Dimming", 4899, "Walnut",
    "Floor lamps and larger decorative pieces. From our Living Room Favorites collection."),
  p("lamp-chrome-retro-floor-lamp", "Chrome Retro Floor Lamp", 6399, "Chrome",
    "Floor lamps and larger decorative pieces. From our Living Room Favorites collection."),
  p("lamp-beige-retro-floor-lamp", "Beige Retro Floor Lamp", 6399, "Beige",
    "Floor lamps and larger decorative pieces. From our Living Room Favorites collection."),
  p("lamp-black-corner-floor-lamp-warm-white", "Black Corner Floor Lamp, Warm White", 9499, "Black",
    "Floor lamps and larger decorative pieces. From our Living Room Favorites collection."),
  p("lamp-contemporary-glass-dining-pendant-white", "Contemporary Glass Dining Pendant, White", 2899, "White",
    "Floor lamps and larger decorative pieces. From our Living Room Favorites collection."),
  p("lamp-contemporary-glass-dining-pendant-black", "Contemporary Glass Dining Pendant, Black", 2899, "Black",
    "Floor lamps and larger decorative pieces. From our Living Room Favorites collection."),
  p("lamp-adjustable-color-modern-dining-pendant", "Adjustable Color Modern Dining Pendant", 2899, "",
    "Floor lamps and larger decorative pieces. From our Living Room Favorites collection."),
];

// Every product: the lamp collections plus every object in the 3D rooms (catalog.ts;
// coming-soon until its CJ listing is imported).
export const products: Product[] = [...lampProducts, ...catalogProducts];

export interface CatalogueCollection {
  slug: string;
  name: string;
  description: string;
  coverImage: string;
  productIds: string[];
}

/** Catalogue departments. Lamps is the only one for now; its collections group by atmosphere. */
export const departments: { slug: string; name: string; image: string; collections: CatalogueCollection[] }[] = [
  {
    slug: "lighting",
    name: "Lighting",
    image: "/images/catalogue/lamps.jpg",
    collections: [
      {
        slug: "modern-essentials",
        name: "Modern Essentials",
        description: "Clean lines, matte finishes, understated design.",
        coverImage: "/images/catalogue/modern-essentials-36e46540.jpg",
        productIds: ["lamp-rechargeable-metal-accent-lamp", "lamp-black-rechargeable-breathing-lamp", "lamp-silver-rechargeable-breathing-lamp", "lamp-black-and-copper-led-table-lamp", "lamp-double-sided-led-touch-lamp", "lamp-white-magnetic-mini-lamp", "lamp-black-magnetic-mini-lamp", "lamp-matte-black-minimalist-wall-light", "lamp-modern-white-circular-wall-light", "lamp-rotating-bedside-led-lamp"],
      },
      {
        slug: "warm-and-cozy",
        name: "Warm & Cozy",
        description: "Soft lighting, inviting bedrooms, warm colors.",
        coverImage: "/images/catalogue/warm-and-cozy-22870117.jpg",
        productIds: ["lamp-walnut-mushroom-bedside-lamp", "lamp-beech-mushroom-bedside-lamp", "lamp-gold-antique-cordless-lamp", "lamp-pleated-walnut-floor-lamp", "lamp-wood-grain-pleated-lamp-warm-light", "lamp-fabric-shade-bedside-lamp", "lamp-dual-usb-fabric-bedside-lamp", "lamp-warm-dimmable-spiral-lamp", "lamp-soft-white-glass-globe-wall-light"],
      },
      {
        slug: "retro-revival",
        name: "Retro Revival",
        description: "Nostalgic shapes, playful colors, vintage influences.",
        coverImage: "/images/catalogue/retro-revival-0b73bb30.jpg",
        productIds: ["lamp-red-retro-metal-table-lamp", "lamp-milk-green-retro-table-lamp", "lamp-chrome-retro-table-lamp", "lamp-beige-retro-table-lamp", "lamp-red-retro-floor-lamp", "lamp-green-retro-floor-lamp", "lamp-retro-glass-shell-wall-lamp-green", "lamp-vintage-wrought-iron-wall-light-black", "lamp-vintage-wrought-iron-wall-light-gold", "lamp-vintage-country-iron-table-lamp"],
      },
      {
        slug: "quiet-luxury",
        name: "Quiet Luxury",
        description: "Glass, gold accents, polished sophistication.",
        coverImage: "/images/catalogue/quiet-luxury-3700279a.jpg",
        productIds: ["lamp-gold-crystal-wall-sconce", "lamp-black-crystal-wall-sconce", "lamp-gold-modern-wall-light-small", "lamp-gold-modern-wall-light-large", "lamp-brushed-gold-circular-sconce", "lamp-coffee-gold-circular-sconce", "lamp-gold-rechargeable-ambient-lamp", "lamp-frosted-glass-globe-wall-lamp-18cm", "lamp-rechargeable-gold-bistro-table-lamp"],
      },
      {
        slug: "nature-inspired",
        name: "Nature Inspired",
        description: "Wood, rattan, earthy finishes.",
        coverImage: "/images/catalogue/nature-inspired-ce285798.jpg",
        productIds: ["lamp-solid-wood-nordic-table-lamp", "lamp-solid-wood-warm-light-lamp-3w", "lamp-solid-wood-warm-light-lamp-5w", "lamp-walnut-finish-wooden-accent-lamp", "lamp-black-wooden-accent-lamp", "lamp-natural-rattan-ball-pendant", "lamp-light-coffee-rattan-pendant", "lamp-orange-toned-rattan-pendant", "lamp-bamboo-woven-chandelier", "lamp-handwoven-bamboo-dining-pendant"],
      },
      {
        slug: "statement-pieces",
        name: "Statement Pieces",
        description: "Bold forms, unusual silhouettes, eye-catching lighting.",
        coverImage: "/images/catalogue/statement-pieces-20e1e897.jpg",
        productIds: ["lamp-magnetic-floating-bulb-lamp-square-base", "lamp-magnetic-floating-bulb-lamp-round-base", "lamp-floating-moon-lamp-brown-base", "lamp-rotating-moon-lamp-gray", "lamp-rotating-moon-lamp-white", "lamp-hot-air-balloon-table-lamp-red", "lamp-hot-air-balloon-table-lamp-blue", "lamp-geometric-resin-wall-lamp-green", "lamp-geometric-resin-wall-lamp-orange"],
      },
      {
        slug: "work-and-focus",
        name: "Work & Focus",
        description: "Task lighting and practical modern desk lamps.",
        coverImage: "/images/catalogue/work-and-focus-28dacd69.jpg",
        productIds: ["lamp-rechargeable-eye-care-desk-lamp-1800mah", "lamp-rechargeable-eye-care-desk-lamp-2500mah", "lamp-plug-in-reading-desk-lamp", "lamp-touch-sensor-reading-lamp-black", "lamp-touch-sensor-reading-lamp-white", "lamp-smart-desk-lamp-with-wireless-charger-black", "lamp-smart-desk-lamp-with-wireless-charger-white", "lamp-led-clock-desk-lamp-with-pen-holder-2000mah", "lamp-led-clock-desk-lamp-with-pen-holder-3200mah", "lamp-portable-rechargeable-lamp-with-flashlight"],
      },
      {
        slug: "mood-makers",
        name: "Mood Makers",
        description: "Color-changing and atmospheric lighting.",
        coverImage: "/images/catalogue/mood-makers-cda8505d.jpg",
        productIds: ["lamp-northern-lights-color-changing-lamp", "lamp-northern-lights-cherry-blossom-lamp", "lamp-aurora-borealis-galaxy-projector", "lamp-16-color-crystal-water-ripple-lamp", "lamp-rechargeable-water-ripple-lamp", "lamp-tricolor-water-ripple-lamp", "lamp-rgb-double-sided-ambient-lamp", "lamp-cloud-silicone-touch-lamp", "lamp-black-rgb-corner-floor-lamp"],
      },
      {
        slug: "urban-edge",
        name: "Urban Edge",
        description: "Architectural, industrial, and dark-accent lighting.",
        coverImage: "/images/catalogue/urban-edge-218b86b4.jpg",
        productIds: ["lamp-concrete-industrial-pendant-small", "lamp-concrete-industrial-pendant-large", "lamp-black-nordic-wall-light-single-head", "lamp-black-architectural-wall-light-large", "lamp-gray-architectural-wall-light-small", "lamp-minimalist-aluminum-up-and-down-wall-lamp", "lamp-brushed-black-circular-wall-sconce", "lamp-black-modern-pendant-small", "lamp-black-modern-pendant-large"],
      },
      {
        slug: "living-room-favorites",
        name: "Living Room Favorites",
        description: "Floor lamps and larger decorative pieces.",
        coverImage: "/images/catalogue/living-room-favorites-3158f520.jpg",
        productIds: ["lamp-black-arc-floor-lamp", "lamp-adjustable-led-reading-floor-lamp", "lamp-walnut-pleated-floor-lamp-remote-dimming", "lamp-chrome-retro-floor-lamp", "lamp-beige-retro-floor-lamp", "lamp-black-corner-floor-lamp-warm-white", "lamp-contemporary-glass-dining-pendant-white", "lamp-contemporary-glass-dining-pendant-black", "lamp-adjustable-color-modern-dining-pendant"],
      },
    ],
  },
  // No products yet: the box links to an "arriving soon" page.
  { slug: "seating", name: "Seating", image: "/images/catalogue/seating-e3042d31.jpg", collections: [] },
  // No products yet: the box links to an "arriving soon" page.
  { slug: "tables", name: "Tables", image: "/images/catalogue/tables-34411c48.jpg", collections: [] },
  // No products yet: the box links to an "arriving soon" page.
  { slug: "storage", name: "Storage", image: "/images/catalogue/storage-5fe9d152.jpg", collections: [] },
  // No products yet: the box links to an "arriving soon" page.
  { slug: "decor-accents", name: "Decor & Accents", image: "/images/catalogue/decor-accents-2ac89745.jpg", collections: [] },
  // No products yet: the box links to an "arriving soon" page.
  { slug: "textiles", name: "Textiles", image: "/images/catalogue/textiles-ee4e97c8.jpg", collections: [] },
  // No products yet: the box links to an "arriving soon" page.
  { slug: "beds-bedroom", name: "Beds & Bedroom", image: "/images/catalogue/beds-bedroom-ce65ab47.jpg", collections: [] },
  { slug: "technology", name: "Technology", image: "/images/catalogue/technology-fb6698dd.jpg", collections: [] },
];
